Add LICENSE to repository and distribution file (#10)
Add LICENSE to repository and distribution file

Also fetch LICENSE file from source repository via `wget`

Fixes #9

Signed-off-by: Daniel Hiller <daniel.hiller.1972@gmail.com>

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -80,22 +80,35 @@ function download_virtctl_binaries() {
 }
 
 function create_release_packages() {
+
+    local tmp_dir current_dir
+    tmp_dir=$(mktemp -d)
+    current_dir=$(pwd)
+    cd "$tmp_dir"
+    wget https://raw.githubusercontent.com/kubevirt/kubevirt/master/LICENSE
+    cd "$current_dir"
+    [ -f "$tmp_dir/LICENSE" ] || (
+        echo "failed to fetch license from original repository"
+        exit 1
+    )
+
     local version
     version="$1"
 
     local release_dir="$BASE_DIR/out/release/$version"
 
     for binary_file in $(get_virtctl_binaries "$1"); do
-        chmod +x "$binary_file"
         [ -f "$binary_file" ] || (
             echo "binary file $binary_file does not exist!"
             exit 1
         )
+        chmod +x "$binary_file"
         release_file_name="${binary_file/*\//}.tar.gz"
         if [ ! -f "$release_dir/$release_file_name" ]; then
             archive_dir="$release_dir/virtctl/"
             mkdir -p "$archive_dir"
             cp "$binary_file" "$archive_dir"
+            cp "$tmp_dir/LICENSE" "$archive_dir"
             (
                 cd "$release_dir" || (
                     echo "directory $release_dir does not exist!"
